version: "3.8"

services:
  bot:
    build: .
    restart: always
    working_dir: /apps
    container_name: telebot
    environment:
      DB_PASS: 11
      DB_HOST: pg
      DB_PORT: 5432
    command: python main.py
    depends_on:
      - pg
  pg:
    image: postgres:15.3-alpine
    restart: always
    container_name: my_postgres
    environment:
      POSTGRES_PASSWORD: 11
    volumes:
      - pg_data:/var/lib/postgres/data
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    restart: always
    container_name: redis_pg
    environment:
      HOST: pg
    ports:
      - "6379:6379"
volumes:
  pg_data: